<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="testingAsync.Tests" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ProtonCompatibility" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="APIServices" />
  </ItemGroup>
</Project>
